### ISSUE TITLE
Change time zone

### ISSUE THREAD

**Issue by daalvasq** [nothans/iot-debugger#6]
The time that are shown in the first column is in UTC and I can’t change it to my current time zone that is UTC-5, please help me

**Comment by nothans** [comment]
Thanks for requesting this enhancement. I added a field for timezone based on the timezones that ThingSpeak supports: https://www.mathworks.com/help/thingspeak/time-zones-reference.html

Just enter the full name of the timezone in the field that works for your offset. ThingSpeak will handle the adjustment of the time based on the timezone supplied and the daylight savings rules.

Demo: https://nothans.github.io/iot-debugger/app/thingspeak.html
